### ISSUE TITLE
Sanitization of user IDs

### ISSUE THREAD

**Issue by wolffg** [Team766/scouting-app#36]
I just created an account where the userid is "; SELECT *".  

I couldn't create an account that had <> in it; I got a "name already taken", which is better than allowing, but you should examine at the code path to see why that is.

"hi" causes an error after account creation.

You render the user ID, so you should be careful with reserved characters.

**Comment by JayAgra** [comment]
It throws a "name already taken" error because it checks that the HTML escaped username is the same as the raw username in the same step in which it makes sure there is no user with the same username. 

auth.rs, lines 37 to 39
```rs
if target_user_temp.is_ok() || create_form.username != html_escape::encode_text(&create_form.username).to_string() {
    return HttpResponse::BadRequest().status(StatusCode::from_u16(400).unwrap()).insert_header(("Cache-Control", "no-cache")).body("{\"status\": \"username_taken\"}");
} else {
```
`target_user_temp` is the attempt at getting a user from the database with the same username.

**Comment by JayAgra** [comment]
I was able to create an account `“help”` and `"help"` and was able to log in without issue.

**Comment by JayAgra** [comment]
Ok so it turns out all the goofy accounts (i.e. SQL statements, quotation marks, etc.) don't cause the server issues, but will prevent a user from submitting data. I think I will go ahead and resolve this by disallowing characters that don't match the regex.

```
^[a-z0-9A-Z_-]{3,32}$
```
strings containing only a-z, A-Z, and 0-9, between 3 and 32 characters, will pass.

<img width="392" alt="Screenshot 2024-02-19 at 11 26 32" src="https://github.com/JayAgra/bearTracks/assets/69493224/790c1a6e-8b22-44ba-b90f-c1f86cd41bc2">
<img width="392" alt="Screenshot 2024-02-19 at 11 27 00" src="https://github.com/JayAgra/bearTracks/assets/69493224/ce6f4b8a-39de-46bd-8b43-3af85a96dc2c">
